### ISSUE TITLE
Crash in Authenticator UI due to missing static method OutlinedTextField

### ISSUE THREAD

**Issue by dehboxturtle** [aws-amplify/amplify-ui-android#28]
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).

### Language and Async Model

Kotlin

### Which UI component?

Other

### Gradle script dependencies

```
android {
    namespace 'com.android.dehboxturtle.playmate'
    compileSdk 33

    defaultConfig {
        applicationId "com.android.dehboxturtle.playmate"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "0.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.4.7'
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    buildToolsVersion '31.0.0'
}

dependencies {
    kapt 'com.google.dagger:hilt-compiler:2.46'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'

    // Amplify core dependency
    implementation 'com.amplifyframework:core-kotlin:2.8.4'
    implementation 'com.amplifyframework:aws-api:2.8.4'
    implementation 'com.amplifyframework:aws-auth-cognito:2.8.4'
    implementation 'com.amplifyframework:aws-api:2.8.4'
    implementation 'com.amplifyframework:aws-storage-s3:2.8.4'
    implementation 'com.amplifyframework.ui:authenticator:1.0.0-dev-preview.0'

    implementation 'com.google.dagger:hilt-android:2.46'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'
    implementation 'androidx.activity:activity-compose:1.7.1'
    implementation platform('androidx.compose:compose-bom:2023.05.01')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-core'
    implementation 'androidx.activity:activity-compose:1.7.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation platform('androidx.compose:compose-bom:2023.05.01')
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
}
```

### Environment information

```
------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Amazon.com Inc. 17.0.7+7-LTS)
OS:           Windows 10 10.0 amd64


```

### Please include any relevant guides or documentation you're referencing

https://ui.docs.amplify.aws/android/connected-components/authenticator

### Describe the bug

I tried out the authenticator UI just now on a new project I tried to set up but I'm running into some issues. Does it require a specific version of compose to function? I tried playing around with my proguard-rules file to see if it was being stripped out but that didn't work a when I examined the dex files for my APK I do see the OutlinedTextField classes and functions in it.
```
Process: com.android.dehboxturtle.playmate, PID: 8511
                 java.lang.NoSuchMethodError: No static method OutlinedTextField(Ljava/lang/String;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Modifier;ZZLandroidx/compose/ui/text/TextStyle;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;ZLandroidx/compose/ui/text/input/VisualTransformation;Landroidx/compose/foundation/text/KeyboardOptions;Landroidx/compose/foundation/text/KeyboardActions;ZILandroidx/compose/foundation/interaction/MutableInteractionSource;Landroidx/compose/ui/graphics/Shape;Landroidx/compose/material3/TextFieldColors;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/material3/OutlinedTextFieldKt; or its super classes (declaration of 'androidx.compose.material3.OutlinedTextFieldKt' appears in /data/app/com.android.dehboxturtle.playmate-I98mhormFzyRYdZlokFL0g==/base.apk)
                 	at com.amplifyframework.ui.authenticator.ui.TextInputFieldKt.TextInputField(TextInputField.kt:45)
                 	at com.amplifyframework.ui.authenticator.ui.AuthenticatorFieldKt.AuthenticatorField(AuthenticatorField.kt:42)
                 	at com.amplifyframework.ui.authenticator.ui.AuthenticatorFormKt.AuthenticatorForm(AuthenticatorForm.kt:49)
                 	at com.amplifyframework.ui.authenticator.ui.SignInKt.SignIn(SignIn.kt:49)
                 	at com.amplifyframework.ui.authenticator.ui.ComposableSingletons$AuthenticatorKt$lambda-2$1.invoke(Authenticator.kt:85)
                 	at com.amplifyframework.ui.authenticator.ui.ComposableSingletons$AuthenticatorKt$lambda-2$1.invoke(Authenticator.kt:85)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at com.amplifyframework.ui.authenticator.ui.AuthenticatorKt$Authenticator$1$2.invoke(Authenticator.kt:122)
                 	at com.amplifyframework.ui.authenticator.ui.AuthenticatorKt$Authenticator$1$2.invoke(Authenticator.kt:115)
...
```

### Code Snippet

in MainActivity#onCreate()
```kotlin
         setContent {
            Authenticator { state ->
                PlayMateTheme {
                    // A surface container using the 'background' color from the theme
                    Surface(
                        modifier = Modifier.fillMaxSize(),
                        color = MaterialTheme.colorScheme.background
                    ) {
                        Greeting("PlayMate")
                    }
                }
            }
        }
        try {
            val session = Amplify.Auth.fetchAuthSession({
                Log.i("AmplifyQuickstart", "Auth session = ${it.isSignedIn}")
            }) {
                Log.i("AmplifyQuickstart", "Failed to fetch auth session: ${it.message}")
            }
        } catch (error: AuthException) {
            Log.e("AmplifyQuickstart", "Failed to fetch auth session", error)
        }

```

### Log output

[cat.txt](https://github.com/aws-amplify/amplify-ui-android/files/11483867/cat.txt)

**Comment by mattcreaser** [comment]
Thanks for the question @dehboxturtle. The `dev-preview.0` version of Authenticator is built using `androidx.compose.material3:material3:1.0.1`. The Compose BOM you're using upgrades that to `1.1.0`, which has an incompatible change to the `OutlinedTextField` API.

You can resolve this issue by changing your dependency to this: `implementation platform('androidx.compose:compose-bom:2023.05.00')`. Note that this will downgrade some Compose libraries (you can find the full list [here](https://developer.android.com/jetpack/compose/bom/bom-mapping)).

We'll be updating to the `1.1.0` material version in our next release, so if you can't downgrade then that upcoming update will also resolve this issue.

Finally, we'll be adding a compatibility table to our README to help clarify these requirements going forward.

Hope that helps! Let me know if you have any further questions.

**Comment by mattcreaser** [comment]
Hey @dehboxturtle please give version `1.0.0-dev-preview.1` a try! It is upgraded to material3 `1.1.0` and includes a few improvements to the UI.

**Comment by dehboxturtle** [comment]
Nice, it looks like that fixed the issue! I'll keep playing with it to see how far I can get!
